---

# Ansible check mode available for this sequence of task only after python-apt installed

- name: update
  apt: { update_cache: True, cache_valid_time: 300 }

- name: Install network relates tools
  vars: { packages: [ ifrename, resolvconf ] }
  apt: { name: "{{ packages }}" }

- name: Install complementary apt tools  
  vars: { packages: [ apt-file ] }
  notify: apt-file update
  apt: { name: "{{ packages }}" }

- name: install convenient small diag tools
  vars: { packages: [ locate, htop, dnsutils ] }
  apt: { name: "{{ packages }}" }

# _pkg(python-dev) is apparently required for _pkg(python-augeas) to
# works (in fact maybe for any dynamic library to be used) and that
# was not that easy to find.

- name: Install augeas related tools
  vars: { packages: [ augeas-tools, python-augeas, python-dev ] }
  apt: { name: "{{ packages }}" }

# parted needed by our partprobe module
#
# all are related to auto disk setup

- name: Install tools needed for disk setup
  vars: { packages: [ parted, cryptsetup, ohai ] }
  apt: { name: "{{ packages }}" }
